### ISSUE TITLE
debian package

### ISSUE THREAD

**Issue by pthomasj** [basler/gst-plugin-pylon#10]
I have added files to create a debian package, and it succeeds in building, however, when it is installed, gstreamer lists the plugin as blacklisted. I am wondering if you might have any advice on whether there is an issue with my configuration. Thank you.

https://github.com/pthomasj/gst-plugin-pylon/tree/debian

**Comment by pthomasj** [comment]
Closing. Did not occur on a fresh installation.

**Comment by michaelgruner** [comment]
May I interest you in creating a PR with the Debian support you added? :)

**Comment by pthomasj** [comment]
Sure.

**Comment by pthomasj** [comment]
I created the PR. There are a lot of automatically generated files from `dh_make` that could probably be removed.
