### ISSUE TITLE
Half screen green when capturing straight to NVMM

### ISSUE THREAD

**Issue by Gabben00** [basler/gst-plugin-pylon#100]
**Describe the bug**
When i capture the data via pylonsrc straight to NVMM with YUY2 half of the screen becomes green, if i go to normal ram first its fine, if i use videotestsrc its fine. 

**To Reproduce**
gst-launch-1.0 videotestsrc ! ‘video/x-raw(memory:NVMM), width=1920, height=1080, framerate=30/1, format=YUY2’! nvvidconv ! ‘video/x-raw(memory:NVMM), width=1920, height=1080, framerate=30/1, format=(string)NV12’ ! nvv4l2h265enc bitrate=2000000 ! h265parse ! queue ! h265parse ! nvv4l2decoder ! nv3dsink -e

**Environment**
 - Basler a2A1920-51gcPRO
 - 0.7.0-15-g86e4ccf
 - Nvidia Xavier Nx 
 - OS: JetPack 5.1.3

**Comment by thiesmoeller** [comment]
The issue has been fixed in the latest release.

On Nvidia you can now easily create a Debian/Ubuntu package https://github.com/basler/gst-plugin-pylon#debian-nvidia-packaging
