### ISSUE TITLE
Is pylon 7.5 supported?

### ISSUE THREAD

**Issue by atomicmac** [basler/gst-plugin-pylon#102]
I see 7.4 is the latest supported release of pylon in the README's support matrix, but 7.5 is the latest available at https://www2.baslerweb.com/en/downloads/software-downloads/#type=pylonsoftware;language=all;version=all

Is 7.5 also supported by this project?

**Comment by thiesmoeller** [comment]
yes. the current release as of today v0.7.1  support pylon 7.5
