### ISSUE TITLE
Would /tests/examples/pylon/howto_decode_meta.py be filled?

### ISSUE THREAD

**Issue by Dueta** [basler/gst-plugin-pylon#114]
Currently the file howto_decode_meta.py and gstpylonmeta.py are both empty. I'm trying to fetch FrameCounter from gst buf meta and here's my probe placing between 'jpegenc' and 'multifilesink'
```python
def on_buffer_probe(self, pad, info, camera_index):
        buf = info.get_buffer()
        if buf:
            meta = pygstpylon.gst_buffer_get_pylon_meta(hash(buf))
            if meta:
                frame_count = meta.chunks.get("FrameCounter")
                if frame_count is not None:
                    print(f"Camera {camera_index} Frame Counter: {frame_count}")
                else:
                    print('no count!')
            else:
                print('no meta!')
        else:
            print('no buf!')
        return Gst.PadProbeReturn.OK
```
 It seems that cannot fetch meta from pygstpylon.gst_buffer_get_pylon_meta(hash(buf)) and printing 'no meta' in terminal. Appreciate for any suggestion!

**Comment by thiesmoeller** [comment]
From which branch you have these files? 

Will provide an example. 
One is in the test folder
