### ISSUE TITLE
Can't set OffsetY or OffsetX

### ISSUE THREAD

**Issue by matthewperkins** [basler/gst-plugin-pylon#12]
Don't seem to be able to change ROI with gst-launch-1.0, can get desired width and height with the caps filter, and other features with UserSet or pfs files, but not the OffsetY or OffsetX, am I missing something obvious?

**Comment by thiesmoeller** [comment]
Please list
*  your camera model
*  Your operating system and 
*  the pipeline you used
*  And if there is an error message a copy of this

**Comment by matthewperkins** [comment]
Camera Model acA-1300-60gc
OS: windows 10
pipeline: 
`
gst-launch-1.0 pylonsrc user-set=UserSet1 cam::OffsetY=400 ! "video/x-
raw,width=1280,height=600,framerate=60/1,format=GRAY8" ! videoconvert ! video/x-raw, format=NV12 ! tee name=t ! queue ! autovideosink t. ! queue ! nvh264enc bitrate=2048 ! h264parse ! mp4mux ! filesink location=E:\\MHP_rig_videos\\test.mp4 -e
`

If I run above pipeline from startup, I get no error.
Adding `cam::CenterY=true ` this shifts the ROI as expected, 

After running with CenterY, if I go back to this pipeline:

`
gst-launch-1.0 pylonsrc user-set=UserSet1 cam::CenterY=false cam::OffsetY=400 ! "video/x-raw,width=1280,height=600,framerate=60/1,format=GRAY8" ! videoconvert ! video/x-raw, format=NV12 ! tee name=t ! queue ! autovideosink t. ! queue ! nvh264enc bitrate=2048 ! h264parse ! mp4mux ! filesink location=E:\\MHP_rig_videos\\test.mp4 -e
`
I get this warning:
`
(gst-launch-1.0:13964): GLib-GObject-WARNING **: 10:48:17.820: g_object_set_is_valid_property: property 'OffsetY' of object class '_Basler_acA1300_60gc_00305329FA55_192_168_200_1_3956' is not writable
`

**Comment by thiesmoeller** [comment]
When setting the center option, the camera calculates the required offset automatically. And this write protects the offset feature 
So it behaves as expected 

Should be  the same behaviour  in pylonviewer

**Comment by matthewperkins** [comment]
But I get the error when I set the CenterY to false.

Either way, I can't seem to get the camera to OffsetY with gstreamer at all. I can change the OffsetY in the pylon viewer, and see a proper offset, but not when I use those features (either as pfs, user set or cam::OffsetY) as arguments to gst-launch

**Comment by thiesmoeller** [comment]
You see a side effect of the way, we currently initialize the gstreamer properties.
This initialization happens after power on state or  user-set and pfs file gets applied and contains if the property is readonly/readwrite and the ranges of it.

Your user-set1 must contain  `CenterY=true` -> this results in the feature OffsetY initialized as being readonly.
We can't change this after initialization of the cam::OffsetY feature

-> Workaround for you: save an updated UserSet1 into your camera where you disabled the CenterY feature and control it from the gstreamer properties.

These dynamic dependencies are one of the main topics in the next releases.

**Comment by thiesmoeller** [comment]
fixed in v0.4.0
