### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by RuthPikovsky** [basler/gst-plugin-pylon#128]
Hello,
I followed the instructions as I tried to install the plugin on my windows computer. I downloaded pylon 8.1 from the site as a developer, downloaded mason meson-1.6.0-64.msi, opened a developer command prompt for vs 2022, and wrote the following commands:
set PKG_CONFIG_PATH=C:\gstreamer\1.0\msvc_x86_64\lib\pkgconfig
set PATH=%PATH%;C:\gstreamer\1.0\msvc_x86_64\bin
set CMAKE_PREFIX_PATH=C:\Program Files\Basler\pylon 8\Development\CMake\pylon\
git clone https://github.com/basler/gst-plugin-pylon.git                         to C:\
cd gst-plugin-pylon
meson setup build --prefix=C:\gstreamer\1.0\msvc_x86_64

I attached the error log file.
[meson-log.txt](https://github.com/user-attachments/files/17791124/meson-log.txt)

note: I used msys64 and not conda because my company doesn't work with anaconda as it is not free anymore and by using msys64 i managed to install g-streamer with no issues, so if possible I would prefer that.

I would appreciate your help,
Thank you in advance,
Ruth Pikovsky

**Comment by thiesmoeller** [comment]
the meson log looks okay on the first glance.

what i need for support is the output of ninja during the build and the error message you see

**Comment by thiesmoeller** [comment]
can you show the cmake_pylon trace  to see why meson .. via cmake .. is not finding pylon folder?

It should be in meson-private folder

**Comment by thiesmoeller** [comment]
Hi @RuthPikovsky, has been solved for you?

The error is, that installed pylon installation is not found

**Comment by RuthPikovsky** [comment]
Hi, unfortunately not, but I managed to successfully install the plugin on a linux computer so it's fine.

Thanks!

**Comment by thiesmoeller** [comment]
As we don't follow up with your issue here, could you please close it?
