### ISSUE TITLE
GST_DEBUG failing over level 3

### ISSUE THREAD

**Issue by Trushantadeshara** [basler/gst-plugin-pylon#22]
The pipeline I am working on is as follow:
GST_DEBUG=2 gst-launch-1.0 -v pylonsrc ! bayer2rgb ! videoconvert ! ximagesink

This works for me but when I change debug level to 3 or higher, I get 
Unable to install property error for my device which is "acA1300-60gc"
At the end I get 'GenICam_3_1_Basler_pylon::AccessException.

**Comment by thiesmoeller** [comment]
Can you attach the log output?

**Comment by thiesmoeller** [comment]
fixed in v0.5.0
