### ISSUE TITLE
BslScalingEnable - Node not writeable

### ISSUE THREAD

**Issue by Notwista** [basler/gst-plugin-pylon#26]
[debug.txt](https://github.com/basler/gst-plugin-pylon/files/10278582/debug.txt)
Using a daA2500-60mc or daA3840-30mc and trying to set the resolution to VGA with BslScaleingEnable = true, I got an error message that the node is not writeable. Here is the pipeline and the debug output:

`# GST_DEBUG=2,pylon*:9 gst-launch-1.0 pylonsrc cam::BslScalingEnable=true ! "video/x-raw, width=640,height=480,format=YUY2" ! vpuenc_h264 ! mpegtsmux name=mux1 ! filesink location=daA3840_640_scaling.ts   `

The same happens, when loading a PFS-file with BslScalingEnable=true. With BslScalingEnable=false the PFS-file loads just fine.

Debug-text attached.

P.S.: when using "`gst-inspect-1.0 pylonsrc`" the naming for SensorWidth and SensorHeight is not correct, . Probably "Width" and "Height" is correct, but "cam::Width=640" has no effect on my side.

**Comment by thiesmoeller** [comment]
cam::BslScalingEnable=true failing is a bug. Thanks for reporting.

Width and height have to be set using standard gstreamer caps filters. See the Readme for details.
Sensor... are read-only properties of the camera listing the maximum sensor resolution

**Comment by thiesmoeller** [comment]
Can you please post the PFS file you used

**Comment by thiesmoeller** [comment]
fixed in release 0.5.1
