### ISSUE TITLE
V0.5.1 ExposureTime/Gain not available for Ace2? 

### ISSUE THREAD

**Issue by constiDisch** [basler/gst-plugin-pylon#32]
Hi,
my system is the following:
* Camera: usb ace2 (a2A3840-45ucBAS)
* Windows
* Pylon 7.1

With gst-plugin-pylon version 0.4.0, `gst-inspect.exe pylonsrc` did show ExposureTime/Gain in the property list.
Since I upgraded to version `0.5.1`  these two properties are missing. I was not able to set those properties in version `0.5.1` in application. In the Pylon Viewer, i can change the properties.

With an ace1 everything works as expected

Do I miss something here?

Thanks a lot
[gst_pylon_logs040.txt](https://github.com/basler/gst-plugin-pylon/files/10683594/gst_pylon_logs040.txt)
[gst_pylon_logs051.txt](https://github.com/basler/gst-plugin-pylon/files/10683595/gst_pylon_logs051.txt)

**Comment by thiesmoeller** [comment]
Is reproduced. Introspection enhancements in 0.5.1 fail on specific ace2 genicam trees.

We'll create a fix.

**Comment by thiesmoeller** [comment]
fixed in rel 0.6.0
