### ISSUE TITLE
gst-inspect and gst-launch hangs with pylonsrc

### ISSUE THREAD

**Issue by aazhuang2** [basler/gst-plugin-pylon#37]
Had an issue with running pylonsrc with an `acA4112-8gmACS`. In which gst-inspect-1.0 and gst-launch-1.0 will hang for ever.

Running `GST_DEBUG=7 gst-inspect-1.0 pylonsrc` will show the following being printed forever,

```
0:00:03.375394130 62113 0x55bbe02f2c00 LOG       GST_PLUGIN_LOADING gstpluginloader.c:1150:exchange_packets: Poll res = 0. 0 bytes pending for write
0:00:03.375420875 62113 0x55bbe02f2c00 DEBUG               GST_POLL gstpoll.c:1241:gst_poll_fd_has_error: 0x55bbe035cc00: fd (fd:8, idx:2) 0
0:00:03.375425291 62113 0x55bbe02f2c00 DEBUG               GST_POLL gstpoll.c:1266:gst_poll_fd_can_read_unlocked: 0x55bbe035cc00: fd (fd:8, idx:2) 0
0:00:03.375428694 62113 0x55bbe02f2c00 DEBUG               GST_POLL gstpoll.c:1195:gst_poll_fd_has_closed: 0x55bbe035cc00: fd (fd:8, idx:2) 0
0:00:03.375433174 62113 0x55bbe02f2c00 DEBUG               GST_POLL gstpoll.c:1414:gst_poll_wait: 0x55bbe035cc00: timeout :0:00:01.000000000
0:00:03.004880865 62114 0x55a3b9f97400 DEBUG               pylonsrc gstpylonintrospection.cpp:644:gst_pylon_find_limits: failed to set action
0:00:03.005573104 62114 0x55a3b9f97400 DEBUG               pylonsrc gstpylonintrospection.cpp:644:gst_pylon_find_limits: failed to set action
0:00:03.006255033 62114 0x55a3b9f97400 DEBUG               pylonsrc gstpylonintrospection.cpp:644:gst_pylon_find_limits: failed to set action
0:00:03.006863032 62114 0x55a3b9f97400 DEBUG               pylonsrc gstpylonintrospection.cpp:644:gst_pylon_find_limits: failed to set action
0:00:03.007512652 62114 0x55a3b9f97400 DEBUG               pylonsrc gstpylonintrospection.cpp:644:gst_pylon_find_limits: failed to set action

...
```

Tested with both gstreamer 1.16 and 1.20.

Ran a `git bisect` to find that this commit https://github.com/basler/gst-plugin-pylon/commit/14ed081d60d807aa2bbf7c049e7e97071364027b, seems to be the cause of the issue. Reverting that commit seems to solve the issue with `gst-inspect-1.0` and `gst-launch-1.0`

**Comment by thiesmoeller** [comment]
@aazhuang2, please check the branch https://github.com/basler/gst-plugin-pylon/tree/feature/ace1_gige_introspection

We've integrated more support to assist the feature mapping from pylon to gstreamer.

**Comment by aazhuang2** [comment]
Hi @thiesmoeller 

Thanks for the update, the `acA4112-8gmACS` managed to run `gst-inspect-1.0` after 6 minutes. I have another camera `a2A5328-4gmBAS` and it took 16 minutes. 
[a2A5328-4gmBAS.zip](https://github.com/basler/gst-plugin-pylon/files/11084463/a2A5328-4gmBAS.zip)


I saw that `gst-pylon` is caching the results, but it seems to be a string of random alphanumeric characters, is there a way to "warm up" the cache on a per camera family basis or transfer it between host machines?

**Comment by thiesmoeller** [comment]
Did you record the trace using `main`  or the updated `feature/ace1_gige_introspection`  branch ?

**Comment by aazhuang2** [comment]
I was using `feature/ace1_gige_introspection`.

**Comment by thiesmoeller** [comment]
Will check your log and verify your camera models

**Comment by thiesmoeller** [comment]
Hi @aazhuang2 
Fixes to the heuristics to speed up a2A gige introspection.

Can you please rebuild with version 0.6.1 and log the trace on your side from a fresh cache:

```bash
# clear gst-plugin-pylon cache
rm -f $HOME/.cache/gstpylon/*
GST_DEBUG=pylonsrc:7 GST_DEBUG_NO_COLOR=1 gst-inspect-1.0 pylonsrc &> pylonsrc_trace_0.6.1.log
```

Target is to understand, why the current code runs on your side an order of magnitude slower than here....

**Comment by aazhuang2** [comment]
[pylonsrc_trace_0.6.1.zip](https://github.com/basler/gst-plugin-pylon/files/11106547/pylonsrc_trace_0.6.1.zip)
With,
```
pylon                          7.2.1.25747-deb0
gst-launch-1.0 version 1.20.6 1.20.6 (GIT)
```

And I am running it in a Ubuntu:20.04 docker container

**Comment by thiesmoeller** [comment]
What is the OS and platform of your host system?
What kind of network is configured for your container ?

**Comment by aazhuang2** [comment]
Host OS is Ubuntu 22.04, and it is the container network is mounted as host.

**Comment by aazhuang2** [comment]
Just ran it on my host machine and it ran in 10 seconds.
Might be a docker issue then?

[pylonsrc_trace_0.6.1_host.zip](https://github.com/basler/gst-plugin-pylon/files/11108348/pylonsrc_trace_0.6.1_host.zip)

**Comment by thiesmoeller** [comment]
you are not running 0.6.1 ( current main ) on your docker

See the version info, that gets printed out by gst-inspect ( header ) : `0.6.0-7-g8e1d83b+`

check your code. and set it to commit HEAD of main, or simply the tag v0.6.1

**Comment by aazhuang2** [comment]
Ah sorry about that, I re-ran both cameras with 0.6.1 in the container,
[pylonsrc_trace_0.6.1_ace1.zip](https://github.com/basler/gst-plugin-pylon/files/11116610/pylonsrc_trace_0.6.1_ace1.zip)
[pylonsrc_trace_0.6.1_ace2.zip](https://github.com/basler/gst-plugin-pylon/files/11116611/pylonsrc_trace_0.6.1_ace2.zip)

The ace2 enumerates in 10 seconds, which is a huge improvement. While the ace still takes ~4min.

**Comment by thiesmoeller** [comment]
your model ace1 is somewhere in between the models that work now. ... more heuristics to come.

What is the start time in your container setup with filled cache?

**Comment by aazhuang2** [comment]
When the cache is filled, it start in ~6 seconds.

[pylonsrc_trace_0.6.1_ace_warm.zip](https://github.com/basler/gst-plugin-pylon/files/11118343/pylonsrc_trace_0.6.1_ace_warm.zip)

**Comment by thiesmoeller** [comment]
Hi, @aazhuang2 

in branch https://github.com/basler/gst-plugin-pylon/tree/feature/ace_fl_gige_introspection more heuristics to speed up introspection on your ...ACS model has been added. Will push  to main soon.

Part of the startup time ~2s is the camera enumeration process over gige and can't be speed up significantly.
The remaining four seconds are under discussion to optimize by a better caching strategy.

**Comment by aazhuang2** [comment]
Hi, @thiesmoeller 

Thanks for the updates, the ace1 is now running in ~15 seconds,  [pylonsrc_trace_e22e26a_ace1.zip](https://github.com/basler/gst-plugin-pylon/files/11165583/pylonsrc_trace_e22e26a_ace1.zip)

I completely understand that there will be a lower bound on the time to enumerate to communicate with the cameras, as even the 15 seconds is a drastic improvement from what was happening before.

**Comment by thiesmoeller** [comment]
All the changes triggered by your request have been integrated to main. 
Thanks for this :-)

The 15s discovery time is only for the first connect, as you are running from the cache ( if you don't delete it )

Refactoring of the introspection code is in the backlog to support better and more fine grained control for specific camera models differences.

Can you close this issue, if it is solved for you now?

**Comment by aazhuang2** [comment]
Yeah, thanks for your help with updating it.
