### ISSUE TITLE
cam:: parameters are not applied (only some work, if pfs file is given)

### ISSUE THREAD

**Issue by martin-petzold** [basler/gst-plugin-pylon#44]
**Describe the bug**

We need to change OffsetX and OffsetY parameters on start and would also like to change these values dynamically during runtime. However, it seems none of the cam:: parameters are applied. We added the parameters as described in the documentation.

It seems to work somehow if a pfs is also added. However, still it is buggy and only some parameters work.

**To Reproduce**

Does not work: `gst-launch-1.0 pylonsrc cam::OffsetX=1144 cam::OffsetY=1016 ! "video/x-raw,format=YUY2,width=1920,height=1080,framerate=30/1" ! queue ! waylandsink`

Works partly (but still some cam:: parameters are not working; in this case cam::OffsetX ist not applied): `gst-launch-1.0 pylonsrc pfs-location=test.pfs cam::OffsetX=1144 cam::OffsetY=1016 ! "video/x-raw,format=YUY2,width=1920,height=1080,framerate=30/1" ! queue ! waylandsink`

[test.pfs.txt](https://github.com/basler/gst-plugin-pylon/files/11353395/test.pfs.txt)

**Expected behavior**

Plugin should apply the parameters without using any pfs file and should also overwrite any defaults.

**Environment**
 - Camera: Basler daA4200-30mci-AF90-AR1335
 - Plugin Version: 0.5.1; Basler/Pylon plugin for pylon SDK 6.2.0 (18677)
 - Platform: i.MX8MP on Custom Board
 - OS: Custom Debian with Custom Kernel 5.10

**Comment by thiesmoeller** [comment]
Hi Martin,

Issue is due a clash of gstreamer pipeline requirements of image dimensions and the camera requirements.
The order of checking and applying these values is currently leading to the failure to apply Offset(X/Y)

Like you found out a static Offset from PFS file works, but your dynamic use case is failing.

Expect a fix in the next days. We currently have two options to solve the issue and will check which one will be best in terms of usability.

**Comment by martin-petzold** [comment]
Thanks! However, I am talking only about OffsetX/Y. The dimensions ("video/x-raw,format=YUY2,width=1920,height=1080,framerate=30/1") are applied. And according to gst-inspect the cam::Width and cam::Height properties are read-only. Which seams reasonable to us.

In a first step we need to use OffsetX/Y, in a later step it would be great if these properties could also be set dynamically in a running pipeline.

**Comment by thiesmoeller** [comment]
Yes width, height and videoformat have to be fixed when capture engine is fully setup. Can be dynamically and statically changed in the range of the available "space" of the current  ROI on the full sensor ROI with our upcoming  fix.

**Comment by martin-petzold** [comment]
Thanks, looking forward to the update. We will test immediately.

**Comment by thiesmoeller** [comment]
We have a version for you to test in branch: https://github.com/basler/gst-plugin-pylon/tree/hotfix/v0.6.2_set_offset_xy_from_props

This only fixes the offsetx/y and width/height interdependencies. 
Other conflicting features ( e.g. Binning/SubSampling/MultiROI )  will be added after some larger refactorings.

**Comment by martin-petzold** [comment]
I can confirm the fix for offsetX/Y with the environment above, but with plugin [v0.6.2_set_offset_xy_from_props](https://github.com/basler/gst-plugin-pylon/tree/hotfix/v0.6.2_set_offset_xy_from_props)

Works: `gst-launch-1.0 pylonsrc cam::OffsetX=1144 cam::OffsetY=1016 ! "video/x-raw,format=YUY2,width=1920,height=1080,framerate=30/1" ! queue ! waylandsink`

**Comment by thiesmoeller** [comment]
Expect a full release next week.

**Comment by martin-petzold** [comment]
Will it also be possible to change these properties (especially offsetX/Y) while the pipeline is active?

**Comment by martin-petzold** [comment]
With this patch the documentation of the properties is missing: `gst-inspect-1.0 pylonsrc`

```
Factory Details:
  Rank                     none (0)
  Long-name                Basler/Pylon source element
  Klass                    Source/Video/Hardware
  Description              Source element for Basler cameras
  Author                   Basler AG <support.europe@baslerweb.com>

Plugin Details:
  Name                     pylon
  Description              Basler/Pylon plugin for pylon SDK 6.2.0(18677)
  Filename                 /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstpylon.so
  Version                  0.6.2-1-g6dd9fe4
  License                  BSD
  Source module            gst-plugin-pylon
  Binary package           GStreamer Pylon Plug-in source release
  Origin URL               https://github.com/basler/gst-plugin-pylon

GObject
 +----GInitiallyUnowned
       +----GstObject
             +----GstElement
                   +----GstBaseSrc
                         +----GstPushSrc
                               +----GstPylonSrc

Implemented Interfaces:
  GstChildProxy

Pad Templates:
  SRC template: 'src'
    Availability: Always
    Capabilities:
      video/x-raw
                 format: { (string)GRAY8, (string)RGB, (string)BGR, (string)YUY2, (string)UYVY }
                  width: [ 1, 2147483647 ]
                 height: [ 1, 2147483647 ]
              framerate: [ 0/1, 2147483647/1 ]
      video/x-bayer
                 format: { (string)rggb, (string)bggr, (string)gbgr, (string)grgb }
                  width: [ 1, 2147483647 ]
                 height: [ 1, 2147483647 ]
              framerate: [ 0/1, 2147483647/1 ]

Element has no clocking capabilities.
Element has no URI handling capabilities.

Pads:
  SRC: 'src'
    Pad Template: 'src'

Element Properties:
  blocksize           : Size in bytes to read per buffer (-1 = default)
                        flags: lesbar, schreibbar
                        Unsigned Integer. Range: 0 - 4294967295 Default: 4096 
  cam                 : The camera to use.
                        According to the selected camera different properties will be available.
                        These properties can be accessed using the "cam::<property>" syntax.
                        The following list details the properties for each camera.
 Basler daA4200-30mci-AF (40185824) Camera:

                                   name                               : The name of the object
                                                                        flags: readable, writable
                                                                        String. Default: "(null)"
                                   parent                             : The parent of the object
                                                                        flags: readable, writable
                                                                        (null)
                                   SensorWidth                        : Width of the camera's sensor in pixels.
                                                                        flags: readable
                                                                        Integer64. Range: -9223372036854775808 - 9223372036854775807 Default: 4208
```

**Comment by thiesmoeller** [comment]
This is the current behaviour, when the camera is currently open in another application.

This will change after the refactoring of the introspection code.
With that change we'll completely run from a cache file. Currently we still have to fully open the the device even for gst-inspect calls.

**Comment by thiesmoeller** [comment]
fixed on main
