### ISSUE TITLE
Caught SIGSEGV Jetson NX

### ISSUE THREAD

**Issue by arun-kumark** [basler/gst-plugin-pylon#55]
**Describe the bug**
I am trying to execute the simple pipeline
`gst-launch-1.0 pylonsrc cam::ExposureTime=20000 cam::Gain=10.3 ! "video/x-raw,width=640,height=480,framerate=10/1,format=GRAY8" ! videoconvert ! autovideosink`

As a result, I see the following SIGSEGV
**arun@arun:~/DeepStream-Yolo$ gst-launch-1.0 pylonsrc cam::ExposureTime=20000 cam::Gain=10.3 ! "video/x-raw,width=640,height=480,framerate=10/1,format=GRAY8" ! videoconvert ! autovideosink
Caught SIGSEGV**
Spinning.  Please run 'gdb gst-launch-1.0 19979' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core

**Environment**
 - Camera: I am using Basler Ace2 camera
 - plugin version info from `gst-inspect-1.0 pylonsrc | grep -E "Descr.*pylon.*|\s+Version\s+[0-9]+"`
 -   Description              Basler/Pylon plugin for pylon SDK 7.3.0(19429)
  Version                  0.7.0

 - Platform: Hardware platform used
 - Jetson NX platform
 - Model: NVIDIA Jetson Xavier NX Developer Kit - Jetpack 5.0.2 GA [L4T 35.1.0]
NV Power Mode[8]: MODE_20W_6CORE
Serial Number: [XXX Show with: jetson_release -s XXX]
Hardware:
 - P-Number: p3668-0001
 - Module: NVIDIA Jetson Xavier NX
Platform:
 - Distribution: Ubuntu 20.04 focal
 - Release: 5.10.104-tegra
jtop:
 - Version: 4.2.1
 - Service: Active
Libraries:
 - CUDA: 11.4.239
 - cuDNN: 8.4.1.50
 - TensorRT: 8.4.1.5
 - VPI: 2.1.6
 - Vulkan: 1.3.203
 - OpenCV: 4.5.2 - with CUDA: NO

I see that its not able to find the pylon on system, but I already installed the Pylon7 from Basler.
I am not sure why this crash ! Could you please help to make the things back to normal again.

thanks
Arun

**Comment by SMA2016a** [comment]
try to pass the following setting   capture-error=skip at pylonsrc

**Comment by arun-kumark** [comment]
Thanks for the suggestion SMA2016a, 
The problem was the network configuration in Pylon viewer and Network settings. Solving the configuration issue result in good pipeline running.
I want to convert the following Pipeline in Python code for my Basler Camera. Do you have suggestion how to write and convert this pipeline to Python file? 
`
gst-launch-1.0 pylonsrc capture-error=skip  pfs-location=example-file-name.pfs cam::ExposureTime=20000 cam::Gain=10.3 ! "video/x-raw(memory:NVMM)" ! videoconvert ! nvvideoconvert ! m.sink_0 nvstreammux name=m batch-size=1 width=640 height=480 ! nvinfer config-file-path=/home/arun/Documents/DeepStream-Yolo/config_infer_primary_yoloV5.txt unique-id=1 ! nvvideoconvert ! nvdsosd ! nvegltransform ! nveglglessink sync=0`

thanks in advance !
