### ISSUE TITLE
could not work on OrangePi5

### ISSUE THREAD

**Issue by lynnqiulin** [basler/gst-plugin-pylon#56]
Previously I successfully installed the gst-plugin-pylon onto BananaPi but due to no available hw encoder I need to switch to OrangePi5. 
However the same install could not work. Not sure what kind of problem it is? After gst-launch-1.0 pylonsrc ! videoconvert ! autovideosink, it quickly quit with below error message:

![image](https://github.com/basler/gst-plugin-pylon/assets/30337870/d0fe54bb-7821-4168-b422-b034aff54f57)
![error](https://github.com/basler/gst-plugin-pylon/assets/30337870/9d930bb1-848e-43f8-ac42-473a0f8e2759)

Any idea what might be the cause? OS is Ubuntu Jammy

**Comment by SMA2016a** [comment]
How many MB free RAM is available on your system?

**Comment by lynnqiulin** [comment]
I fixed the issue, it is due to OrangePi5 USB3 port power supply issue. When change it to USB typec port it works fine now.
