### ISSUE TITLE
Report failed to start camera while trying to reconnect to Gstreamer-rtsp-server

### ISSUE THREAD

**Issue by tianyi-lu-ocean** [basler/gst-plugin-pylon#59]
I am playing with Basler darts camera and trying to encode it and send stream over rtsp from Raspberry pi 4. I tried to the following pipeline:

> (pylonsrc ! "video/x-raw,width=640,height=480,framerate=10/1,format=GRAY8" ! videoconvert ! "video/x-raw,format=I420" ! avenc_mpeg4 ! rtpmp4vpay config-interval=1 name=pay0 pt=96)
> 

then, it works fine.

However, when I tried to use `x264enc `, 

> ( pylonsrc ! "video/x-raw,width=640,height=480,framerate=10/1,format=GRAY8" ! videoconvert ! "video/x-raw,format=I420" ! x264enc ! rtph264pay config-interval=1 name=pay0 pt=96 )

then, it will show up some error message like this when a client is trying to request the stream:

> stream ready at rtsp://127.0.0.1:8554/test
> 0:00:06.333204859 28374      0xacfbc60 ERROR             rtspclient rtsp-client.c:2187:handle_play_request: client 0xad083b0: media not found
> 0:00:06.334283006 28374      0xacfbc60 ERROR             rtspclient rtsp-client.c:1522:handle_teardown_request: client 0xad083b0: no media for uri
> 0:00:07.808557989 28374      0xacfbc60 WARN               rtspmedia rtsp-media.c:4885:gst_rtsp_media_set_state: media 0x7fb40f31c0 was not prepared
> 0:00:07.825773881 28374   0x7fb4003b00 WARN                pylonsrc gstpylonsrc.cpp:820:gst_pylon_src_start:<pylonsrc1> error: Failed to start camera.
> 0:00:07.825926389 28374   0x7fb4003b00 WARN                pylonsrc gstpylonsrc.cpp:820:gst_pylon_src_start:<pylonsrc1> error: TLFactory not instanciated, you must call PylonInitialize()
> 0:00:07.826059155 28374   0x7fb4003b00 WARN                 basesrc gstbasesrc.c:3556:gst_base_src_start:<pylonsrc1> error: Failed to start
> 0:00:07.826145696 28374   0x7fb4003b00 WARN                 basesrc gstbasesrc.c:3912:gst_base_src_activate_push:<pylonsrc1> Failed to start in push mode
> 0:00:07.826192828 28374   0x7fb4003b00 WARN                GST_PADS gstpad.c:1142:gst_pad_set_active:<pylonsrc1:src> Failed to activate pad
> 0:00:07.826665408 28374   0x7fb4003b00 WARN               rtspmedia rtsp-media.c:3555:start_preroll: failed to preroll pipeline
> 0:00:07.826741060 28374   0x7fb4003b00 WARN               rtspmedia rtsp-media.c:3743:start_prepare: failed to preroll pipeline
> 0:00:07.826803378 28374      0xacfbc60 WARN               rtspmedia rtsp-media.c:3576:wait_preroll: failed to preroll pipeline
> 0:00:07.826836713 28374      0xacfbc60 WARN               rtspmedia rtsp-media.c:3946:gst_rtsp_media_prepare: failed to preroll pipeline
> 0:00:07.827567083 28374      0xacfbc60 ERROR             rtspclient rtsp-client.c:1087:find_media: client 0xad08630: can't prepare media
> 0:00:07.828193282 28374      0xacfbc60 ERROR             rtspclient rtsp-client.c:3346:handle_describe_request: client 0xad08630: no media
> 0:00:11.892276118 28374      0xad099e0 WARN                pylonsrc gstpylonsrc.cpp:820:gst_pylon_src_start:<pylonsrc2> error: Failed to start camera.
> 0:00:11.892408865 28374      0xad099e0 WARN                pylonsrc gstpylonsrc.cpp:820:gst_pylon_src_start:<pylonsrc2> error: TLFactory not instanciated, you must call PylonInitialize()
> 0:00:11.892693861 28374      0xad099e0 WARN                 basesrc gstbasesrc.c:3556:gst_base_src_start:<pylonsrc2> error: Failed to start
> 0:00:11.892890871 28374      0xad099e0 WARN                 basesrc gstbasesrc.c:3912:gst_base_src_activate_push:<pylonsrc2> Failed to start in push mode
> 0:00:11.893019637 28374      0xad099e0 WARN                GST_PADS gstpad.c:1142:gst_pad_set_active:<pylonsrc2:src> Failed to activate pad
> 0:00:11.894260329 28374      0xad099e0 WARN               rtspmedia rtsp-media.c:3555:start_preroll: failed to preroll pipeline
> 0:00:11.894434763 28374      0xad099e0 WARN               rtspmedia rtsp-media.c:3743:start_prepare: failed to preroll pipeline
> 0:00:11.895275009 28374      0xacfbe40 WARN               rtspmedia rtsp-media.c:3576:wait_preroll: failed to preroll pipeline
> 0:00:11.895405646 28374      0xacfbe40 WARN               rtspmedia rtsp-media.c:3946:gst_rtsp_media_prepare: failed to preroll pipeline
> 0:00:11.895704587 28374      0xad099e0 WARN               rtspmedia rtsp-media.c:3250:default_handle_message: 0x7f7c00c1e0: got error Failed to start camera. (../ext/pylon/gstpylonsrc.cpp(820): gst_pylon_src_start (): /GstPipeline:media-pipeline/GstBin:bin2/GstPylonSrc:pylonsrc2:
> TLFactory not instanciated, you must call PylonInitialize())
> 0:00:11.895989638 28374      0xad099e0 WARN               rtspmedia rtsp-media.c:3250:default_handle_message: 0x7f7c00c1e0: got error GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure. (../libs/gst/base/gstbasesrc.c(3556): gst_base_src_start (): /GstPipeline:media-pipeline/GstBin:bin2/GstPylonSrc:pylonsrc2:
> Failed to start)
> 0:00:11.897624442 28374      0xacfbe40 ERROR             rtspclient rtsp-client.c:1087:find_media: client 0xad084f0: can't prepare media
> 0:00:11.899197540 28374      0xacfbe40 ERROR             rtspclient rtsp-client.c:3064:handle_setup_request: client 0xad084f0: media '/test' not found
> 0:00:11.939079399 28374      0xacfbe40 WARN                pylonsrc gstpylonsrc.cpp:820:gst_pylon_src_start:<pylonsrc3> error: Failed to start camera.
> 0:00:11.939241907 28374      0xacfbe40 WARN                pylonsrc gstpylonsrc.cpp:820:gst_pylon_src_start:<pylonsrc3> error: TLFactory not instanciated, you must call PylonInitialize()
> 0:00:11.939400360 28374      0xacfbe40 WARN                 basesrc gstbasesrc.c:3556:gst_base_src_start:<pylonsrc3> error: Failed to start
> 0:00:11.939518421 28374      0xacfbe40 WARN                 basesrc gstbasesrc.c:3912:gst_base_src_activate_push:<pylonsrc3> Failed to start in push mode
> 0:00:11.939580554 28374      0xacfbe40 WARN                GST_PADS gstpad.c:1142:gst_pad_set_active:<pylonsrc3:src> Failed to activate pad
> 0:00:11.940548362 28374      0xacfbe40 WARN               rtspmedia rtsp-media.c:3555:start_preroll: failed to preroll pipeline
> 0:00:11.940627847 28374      0xacfbe40 WARN               rtspmedia rtsp-media.c:3743:start_prepare: failed to preroll pipeline
> 0:00:11.940729927 28374      0xad099e0 WARN               rtspmedia rtsp-media.c:3576:wait_preroll: failed to preroll pipeline
> 0:00:11.940800615 28374      0xad099e0 WARN               rtspmedia rtsp-media.c:3946:gst_rtsp_media_prepare: failed to preroll pipeline
> 0:00:11.942314080 28374      0xad099e0 ERROR             rtspclient rtsp-client.c:1087:find_media: client 0xad08770: can't prepare media
> 0:00:11.943336484 28374      0xad099e0 ERROR             rtspclient rtsp-client.c:3346:handle_describe_request: client 0xad08770: no media

Could you please help me walk through this error? Thanks in advance.

**Comment by thiesmoeller** [comment]
Do you shutdown and restart the pylonsrc in your program ?

We seem to have an issue here.

**Comment by tianyi-lu-ocean** [comment]
> Do you shutdown and restart the pylonsrc in your program ?
> 
> We seem to have an issue here.

I am sorry, should be more clarified. I actually used the gstreamer-rtsp-server module and just build their example `test-launch.c`, then gave it the pipeline arguments while it is starting up. I guess it was the rtsp-client, if they received something like,

> Real Time Streaming Protocol
>     Response: RTSP/1.0 503 Service Unavailable\r\n
>         Status: 503
>     CSeq: 0\r\n
>     Server: GStreamer RTSP server\r\n
>     Date: Wed, 26 Jul 2023 21:50:50 GMT\r\n
>     \r\n
 
it will re-send the request, probably, at that moment, the rtsp server will shutdown the plugin and restart it?

**Comment by thiesmoeller** [comment]
I can provide a quick patch tomorrow that removes a workaround for an issue in pylon 7.3.0 on Linux that would raise an error on plugin unload.
The side effect of this workaround currently creates this issue you see.

**Comment by tianyi-lu-ocean** [comment]
Really appreciate it, I have a new update here, I tried to use `gst-luanch-1.0` not `rtsp-server` to generate a `rtp `stream, and then created a` .sdp` file to play the stream on client side, which works fine, the pipeline I ran is below,

>  gst-launch-1.0 pylonsrc ! "video/x-raw,width=640,height=480,framerate=10/1,format=GRAY8" ! videoconvert ! "video/x-raw,format=I420" ! x264enc ! rtph264pay config-interval=1 name=pay0 pt=96 ! udpsink host=127.0.0.1 port=1234

Then, I tried to play with `gst-rtsp-server` one more time, and set up a higher `ipv4-timeout` as 10s, then it will work fine. So, my assumption is that it will take longer to prepare the media since I switched the x264 encoder, I also observed that it also take a while for `pylonsrc` initializing the camera, so, that could also explain why even though I used `avenc_mpeg4` as encoder, it will also show up some error sometimes. Generally speaking, my solution right now is just increasing the time out on client side and since this issue has been resolved, so I am going to close it, but if you guys have more sophisticated way to resolve this, please feel free to leave any comments in this thread.

**Comment by tianyi-lu-ocean** [comment]
I apologize that I have to reopen this issue. Because after resolving the encoder issue, I encountered another issue which I guess is somehow related to the side effect you just mentioned before. 

The problem is, 
I disconnected the client and it seems like the server will unload the plugin and when I tried to reconnect that it will show up the error: `Failed to start camera`. More detail log info as below,

> 0:00:40.595045938 38588      0xe97bc60 WARN               rtspmedia rtsp-media.c:4885:gst_rtsp_media_set_state: media 0x7f9c2d11f0 was not prepared
> 0:01:06.784004955 38588   0x7f9c510800 WARN                pylonsrc gstpylonsrc.cpp:820:gst_pylon_src_start:<pylonsrc1> error: Failed to start camera.
> 0:01:06.784158614 38588   0x7f9c510800 WARN                pylonsrc gstpylonsrc.cpp:820:gst_pylon_src_start:<pylonsrc1> error: TLFactory not instanciated, you must call PylonInitialize()
> 0:01:06.784611778 38588   0x7f9c510800 ERROR               pylonsrc gstpylonsrc.cpp:1026:gst_pylon_src_child_proxy_get_child_by_name:<pylonsrc1> Please specify a camera before attempting to set Pylon device properties

**Comment by thiesmoeller** [comment]
see this hotfix branch `feature/hotfix_pylon_terminate`, that reverts the pylon 7.3.0 terminate code, which ( as described above ) is currently broken regarding multiple restarts of the source.

https://github.com/basler/gst-plugin-pylon/tree/feature/hotfix_pylon_terminate

**Comment by tianyi-lu-ocean** [comment]
> see this hotfix branch `feature/hotfix_pylon_terminate`, that reverts the pylon 7.3.0 terminate code, which ( as described above ) is currently broken regarding multiple restarts of the source.
> 
> https://github.com/basler/gst-plugin-pylon/tree/feature/hotfix_pylon_terminate

Appreciate it. It perfectly solves this issue. I am going to close it.

**Comment by thiesmoeller** [comment]
Great ... So we only have to fix it properly on main ;-)

**Comment by omerts** [comment]
> Really appreciate it, I have a new update here, I tried to use `gst-luanch-1.0` not `rtsp-server` to generate a `rtp `stream, and then created a` .sdp` file to play the stream on client side, which works fine, the pipeline I ran is below,
> 
> > gst-launch-1.0 pylonsrc ! "video/x-raw,width=640,height=480,framerate=10/1,format=GRAY8" ! videoconvert ! "video/x-raw,format=I420" ! x264enc ! rtph264pay config-interval=1 name=pay0 pt=96 ! udpsink host=127.0.0.1 port=1234
> 
> Then, I tried to play with `gst-rtsp-server` one more time, and set up a higher `ipv4-timeout` as 10s, then it will work fine. So, my assumption is that it will take longer to prepare the media since I switched the x264 encoder, I also observed that it also take a while for `pylonsrc` initializing the camera, so, that could also explain why even though I used `avenc_mpeg4` as encoder, it will also show up some error sometimes. Generally speaking, my solution right now is just increasing the time out on client side and since this issue has been resolved, so I am going to close it, but if you guys have more sophisticated way to resolve this, please feel free to leave any comments in this thread.

Raising the timeout saved me a lot of time thanks a lot. This should be documented, I wasted hours on trying to understand why there is no stream.
