### ISSUE TITLE
Not working with Camera Emulation?

### ISSUE THREAD

**Issue by stevenscholz** [basler/gst-plugin-pylon#6]
Hey, 

nice work!

But camera "Basler Emulation (0815-0000)" does not show up with "gst-inspect-1.0 pylonsrc".

Will it work with the "Basler Camera Emulation" for evaluation purposes in future?

Thanks a million,

Steven

**Comment by thiesmoeller** [comment]
@stevenscholz thanks for the feedback.

The camera emulation has to be explicitly enabled for SDK applications https://docs.baslerweb.com/pylonapi/net/Guide#camera-emulation

Only the Basler pylon viewer has it enabled by default.
