### ISSUE TITLE
gst-launch-1.0 pylonsrc cam::TriggerSource-FrameStart=Line1 cam::TriggerMode-FrameStart=On 

### ISSUE THREAD

**Issue by lynnqiulin** [basler/gst-plugin-pylon#62]
When I use this command to specify trigger source as hardware trigger from Line3, the pipeline can be controlled to start playing by Line3 signal, however the frame rate won't change according to hardware trigger signal frequency. Could developer confirm whether frame rate can change according to hardware trigger signal from GPIO or not?

**Comment by thiesmoeller** [comment]
Hi @lynnqiulin,

to set the framerate, you don't have to recompile. Framerate is part of normal gstreamer caps negotiation process.
See e.g. https://github.com/basler/gst-plugin-pylon/blob/2fba87f9b329d90adc70e4cac4c6e075a37d2027/README.md?plain=1#L88

The position in the code is the fallback for the case that no framerate is given. ( neither as capsfilter nor by one of the downstream sinks)

-- 

Gstreamer normally assumes a fixed framerate video stream. In your case of changing the fps by changing the trigger frequency will work, but downstream plugins might 'complain' about framerate issues.

In your setup with a triggered camera, you should set a framerate, that is above your trigger frequency.
As the framerate you give will be the maximum framerate the camera can handle.

**Comment by lynnqiulin** [comment]
Hi @thiesmoeller 
Thank you for the help. 

In my user case, I will first start gstreamer and initial camera with setting saved in user-set, set the camera to hardware trigger, waiting for outside signal to start hardware trigger. So the gstreamer will first start with a framerate but at that time pineline is not set to PLAYING. After that there will be hardware trigger signal. Will this confuse the downstream plugins, or will the downstream plugin's framerate been set to some freqency  like 30Hz as  'no framerate is given' and then won't change?

I follow the guide to set framerate on command line as 60Hz which is higher than hardware trigger setting to rate less than 60Hz. However the output file frame rate is still 60Hz. **Is there anything not correct with my command or flow**?
1. Case 1:
    a. command line: 
    gst-launch-1.0 pylonsrc ! "video/x-raw,framerate=60/1" ! videoconvert ! mpph265enc ! h265parse ! matroskamux ! filesink location=FR40TR20.mp4
    b. start pwm signal of 20Hz/30Hz/40Hz...
    c. result frame rate of mp4 file is 60Hz.
2. Case 2:
    a. command line:
     gst-launch-1.0 pylonsrc ! videoconvert ! mpph265enc ! h265parse ! matroskamux ! filesink location=FRNATR20.mp4
    b. start pwm signal of 20Hz/25Hz/...
    c. result frame rate of mp4 file is 30Hz 
        (guess due to setting in ext/pylon/gstpylonsrc.cpp:614  static const gint preferred_framerate_num = 30;)

**Comment by lynnqiulin** [comment]
I set the frame rate same as trigger frequency, now result frame rate of output file matches. Thank you.
