### ISSUE TITLE
Unable to build on Linux / Jetson Orin

### ISSUE THREAD

**Issue by goncalog** [basler/gst-plugin-pylon#71]
**Describe the bug**
While following the Linux build steps from the README, I'm getting this error after running `meson setup builddir --prefix /usr/`:

`tests/check/meson.build:24:35: ERROR: Could not get pkg-config variable and no default provided for <PkgConfigDependency gstreamer-1.0: True ['>= 1.0.0']>` 

Here's the entire log: 
[meson-log.txt](https://github.com/basler/gst-plugin-pylon/files/13428134/meson-log.txt)

I've checked the pkg-config Path and confirmed that `gstreamer-1.0.pc` is available in the default pkg-config search path.

What else can I try?

**Expected behavior**
Build step should succeed.

**Environment**
 - Camera: Basler daA1920-160uc (40093492)
 - plugin version info from `gst-inspect-1.0 pylonsrc | grep -E "Descr.*pylon.*|\s+Version\s+[0-9]+"`: n.a. but trying to build 7.4.0 (https://www2.baslerweb.com/media/downloads/software/pylon_software/pylon_7_4_0_14900_linux_aarch64_debs.tar.gz)
 - Platform: Jetson AGX Orin - Jetpack 5.1 [LT4 35.2.1]
 - OS: Ubuntu 20.04.6 LTS (GNU/Linux 5.10.104-tegra aarch64)

**Comment by lio94** [comment]
I have the same problem, both on AGX Orin / JP 5.1.1 and x86_64 Ubuntu 20.04 installation with Pylon 7.2.1.

**Comment by snaggas** [comment]
I had a similar issue with the Windows build, which I got past. Unfortunately I'm not sure what resolved it because I was trying various things...

**Comment by thiesmoeller** [comment]
Will provide a first fix to build for pylon 7.4 today.

**Comment by goncalog** [comment]
morning @thiesmoeller, thank you so much for looking into this! do you have any updates?

**Comment by thiesmoeller** [comment]
@goncalog
Quick first:

for pylon 7.4.0 you currently have to use the branch: 
`feature/fix_build_on_pylon7.4.0`

And you have to downgrade meson to 1.0.0

`pip3 install meson==1.0.0`

**Comment by goncalog** [comment]
thank you, will give that a try!

**Comment by thiesmoeller** [comment]
we found the conflicting change in meson: https://github.com/mesonbuild/meson/pull/12126

**Comment by thiesmoeller** [comment]
You are currently mixing meson versions.

For reconfigure meson uses data in the build folder.
Just delete the build folder first in this case.

On the fixes for 7.4.0 branch there is a commit now which fixes the meson issue

**Comment by goncalog** [comment]
all good now, thank you!
