### ISSUE TITLE
Jetpack 5.1 Pylon 7.2.1 Version build Error

### ISSUE THREAD

**Issue by jooyeop** [basler/gst-plugin-pylon#72]
**Jetpack 5.1 version, pylon 7.2.1 version**

meson setup builddir --prefix /usr/.

tests/check/meson.build:24:35: ERROR: Could not get pkg-config variable and no default provided for <PkgConfigDependency gstreamer-1.0: True ['>= 1.0.0']>

meson setup builddir -- prefix /usr/.
The above error occurs when the build proceeds.

Terminal Input : pkg-config --variable=pcfiledir gstreamer-1.0
Output : /usr/lib/aarch64-linux-gnu/pkgconfig

As you can see above, the pkg-config route comes out well without any problems.

**Just in case, I just retried to version 7.4, but the same error occurred.**

**On other Jetpack 5.0.1 devices, it proceeds without problems.**
Help Me

**Comment by thiesmoeller** [comment]
The error has been introduced due to changes in meson.

As a workaround downgrade to meson 1.0.0

`pip3 install meson==1.0.0`
