### ISSUE TITLE
setting the exposure time too high may time out the image grab

### ISSUE THREAD

**Issue by pthomasj** [basler/gst-plugin-pylon#8]
I don't have a minimal working example, so this may just be an issue with my code. The source is here: https://git.ligo.org/patrick.thomas/gige-gst-epics

This allows the remote setting of the exposure time through an EPICS process variable (https://epics.anl.gov/). I am using it with a Basler acA720-290gm GigE camera. If the pipeline is running and I set the exposure time to the maximum of the range (10000000) then it reports an error and closes:

```
** (gige_gst_epics:27536): CRITICAL **: 08:59:51.340: gst_plyon_src_add_metadata: assertion 'buf' failed
Error received from element pylonsrc: Failed to create buffer.
Debugging information: ../ext/pylon/gstpylonsrc.c(704): gst_pylon_src_create (): /GstPipeline:pipeline/GstPylonSrc:pylonsrc:
Grab timed out. Possible reasons are: The image transport from the camera device is not working properly, e.g., all GigE network packets for streaming are dropped; The camera uses explicit triggering (see TriggerSelector for more information) and has not been triggered; Single frame acquisition mode is used and one frame has already been acquired; The acquisition has not been started or has been stopped.
```

My guess is that the exposure time is just longer than the image grab timeout time. Is the image grab timeout time configurable through the plugin?

**Comment by thiesmoeller** [comment]
As a quick workaround set timeout to -1 or any large enough value in https://github.com/basler/gst-plugin-pylon/blob/8eea4201a99a9537bd4f721d111465c110ba677e/ext/pylon/gstpylon.cpp#L299

We'll provide a proper fix soon

**Comment by pthomasj** [comment]
Thank you!

**Comment by thiesmoeller** [comment]
With our latest release of today we've fixed your issue.
There is _no_ timeout on grabbing images.
Commit 6be56609b8722c3c522b0da3684c47f763e795dd  changed the way we grab images from pylon.

**Comment by pthomasj** [comment]
Thank you!
