### ISSUE TITLE
Trying to set the BslBrightness feature to a decimal value

### ISSUE THREAD

**Issue by rbnrtg** [basler/gst-plugin-pylon#80]
As in the example shown in the Features section of the GitHub post, I'm trying to modify the value of the BslBrightness feature of pylonsrc as follows:

gst-launch-1.0 pylonsrc cam::BslBrightness=0.9 ! videoconvert ! autovideosink

But this parameter is only modified when the indicated value is -1, 0 or 1, but when it is a decimal value it cannot be modified from the plugin. 

Is there any way to modify this feature with decimal values?

**Comment by rbnrtg** [comment]
My camera is Basler daA3840-45uc (USB Model)

**Comment by rbnrtg** [comment]
Any update? @thiesmoeller 
Thank you

**Comment by thiesmoeller** [comment]
What is the platform.

Can you call your pipeline with
GST_DEBUG=pylonsrc:10 ...

And post the output. And the error message you get when setting the value

**Comment by rbnrtg** [comment]
I am testing both on x86 and ARM.

When I call these pipelines I do not receive any error but if I set the BslBrightness parameter to 1, it is modified, but if I set it to 0.9, it is not modified.

This is the output when BslBrightness=1: 
**GST_DEBUG=pylonsrc:10 gst-launch-1.0 pylonsrc cam::BslBrightness=1 ! videoconvert ! autovideosink**
`INFO pylonsrc gstpylonobject.cpp:256:gst_pylon_object_set_pylon_feature<double (*)(const _GValue*), Pylon::CFloatParameter>: Set Feature BslBrightness: 1.000`

But when i set BslBrightness=0.9, the output is:
**GST_DEBUG=pylonsrc:10 gst-launch-1.0 pylonsrc cam::BslBrightness=0.9 ! videoconvert ! autovideosink**
`INFO pylonsrc gstpylonobject.cpp:256:gst_pylon_object_set_pylon_feature<double (*)(const _GValue*), Pylon::CFloatParameter>: Set Feature BslBrightness: 0.000`

And my question is that BslBrightness is supposed to allow decimal values between -1 and 1.

Thank you

**Comment by thiesmoeller** [comment]
can reproduce. the feature is clipped to integer values. so -1, 0, +1 work as you describe

We'll work on fix.

**Comment by thiesmoeller** [comment]
argh! this was quick to fix. an older refactoring broke all float features and the tests didn't catch this.
please try the branch feature/fix_build_on_pylon7.4.0

**Comment by thiesmoeller** [comment]
Code is now on main
