### ISSUE TITLE
Unable to build 7.4.0 with NVMM support on Linux / Jetson Orin

### ISSUE THREAD

**Issue by goncalog** [basler/gst-plugin-pylon#82]
**Describe the bug**
While following the Linux build steps from the README I'm unable to compile the `pylonsrc` element with NVMM support enabled:
```
Library nvbufsurface found: YES
Run-time dependency CUDA (modules: cudart_static, rt, pthread, dl) found: NO (tried system)
Message: Deepstream or CUDA not found, skipping NVMM support
```
This happens despite running the steps inside a container with (DeepStream and) CUDA. The container I'm running is based on the `nvcr.io/nvidia/deepstream-l4t:6.2-base` docker image which installs both of those dependencies. And `LD_LIBRARY_PATH` is pointing correctly to `/workspace/lib:/usr/local/cuda-11.4/lib64`. 

Should the modules `cudart_static, rt, pthread, dl` be found in `/usr/local/cuda-11.4/lib64`? They aren't in my case.

**Expected behavior**
Build with NVMM support enabled.

**Environment**
 - Camera: Basler daA1920-160uc (40093492)
 - plugin version info from `gst-inspect-1.0 pylonsrc | grep -E "Descr.*pylon.*|\s+Version\s+[0-9]+"` n.a. but trying to build 7.4.0 (https://www2.baslerweb.com/media/downloads/software/pylon_software/pylon_7_4_0_14900_linux_aarch64_debs.tar.gz)
 - Platform: Jetson AGX Orin - Jetpack 5.1 [LT4 35.2.1]
 - OS: Ubuntu 20.04.6 LTS (GNU/Linux 5.10.104-tegra aarch64)

**Comment by goncalog** [comment]
Yes, looking at the `meson` code (see below) it seems it expects those modules to be found in `/usr/local/cuda-11.4/lib64`:

from _cuda.py_
```
       if not any(runtime in self.requested_modules for runtime in ['cudart', 'cudart_static']):
            # By default, we prefer to link the static CUDA runtime, since this is what nvcc also does by default:
            # https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#cudart-none-shared-static-cudart
            req_modules = ['cudart']
            if kwargs.get('static', True):
                req_modules = ['cudart_static']
                machine = self.env.machines[self.for_machine]
                if machine.is_linux():
                    # extracted by running
                    #   nvcc -v foo.o
                    req_modules += ['rt', 'pthread', 'dl']
            self.requested_modules = req_modules + self.requested_modules
```

And your build also expects `cuda_runtime.h` to be there too. Otherwise one gets the error: `./ext/pylon/gstpylon.cpp:38:12: fatal error: cuda_runtime.h: No such file or directory`. 

I suspect this means we need to install the full CUDA Toolkit rather than relying on the libs that come with the Nvidia's DS docker image (i.e. `nvcr.io/nvidia/deepstream-l4t:6.2-base`). Is this correct @thiesmoeller, or is there an alternative? Thank you!

**Comment by thiesmoeller** [comment]
It was working before the new jetson containers have been introduced

Overall you need the deepstream and cuda-rt development packages.

```bash
apt-get update
apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev cmake cuda-cudart-dev-11-4 deepstream-6.2
# download pylon debian installers
tar -xvf pylon_7_4_0_14900_linux_aarch64_debs.tar.gz 
apt-get install ./*.deb
# install python tools
pip3 install meson ninja
#
git clone https://github.com/basler/gst-plugin-pylon.git
cd gst-plugin-pylon/
PYLON_ROOT=/opt/pylon/ meson setup build
```

In my env this is still failing to build because the relevant file in `/opt/nvidia/deepstream/deepstream/lib` is only a sym-link to the real libs that are missing.

``` 
 libnvbufsurface.so -> /usr/lib/aarch64-linux-gnu/tegra/libnvbufsurface.so
 libnvbufsurftransform.so -> /usr/lib/aarch64-linux-gnu/tegra/libnvbufsurftransform.so
``` 


In the native environment they should be available.

If this is not working on your side, like for me ( still working to find the right package for the lib )
Official source for these packages are typically nvidia_drivers packages

**Comment by goncalog** [comment]
hi @thiesmoeller, we managed to compile it by using a different docker image (ds6.2 triton) and adding the missing libs you mention. thank you

**Comment by kostastsing** [comment]
Hi @goncalog. I am experiencing the same problem when trying to install the plugin in `deepstream-l4t:6.4-triton-multiarch`. I have changed the code in [meson.build](https://github.com/basler/gst-plugin-pylon/blob/main/ext/pylon/meson.build#L16) to point to `/usr/lib/aarch64-linux-gnu/tegra/` for finding `libnvbufsurface.so` but I am always getting that `Library nvbufsurface found: NO`. How do you manage to resolve the problem?
