### ISSUE TITLE
no property cam::DeviceUserID in object pylonsrc

### ISSUE THREAD

**Issue by pthomasj** [basler/gst-plugin-pylon#9]
If I attempt to read the `cam::DeviceUserID` property, then I receive the error in the title. Is there another way to read this?

**Comment by thiesmoeller** [comment]
What is your camera model ?

**Comment by pthomasj** [comment]
acA720-290gm

**Comment by pthomasj** [comment]
The property is available through the Pylon viewer:

![Screenshot_2022-08-23_12-41-28](https://user-images.githubusercontent.com/99351869/186251500-376a79dc-b583-44f0-8dcd-3ca60e4b08a1.png)

**Comment by thiesmoeller** [comment]
At the moment we only map features to gstreamer that would be saved with the Savefeatures function of Basler pylon viewer.
DeviceUserID is a feature that is normally meant to be written by Basler pylon viewer.

**Comment by thiesmoeller** [comment]
you can now read and write any camera feature ( except command features ) from gstreamer.
Commit 445982dd5757bcaa6f45c90b16d7285f22efb9a8 dropped the limitation on streamable features.

**Comment by pthomasj** [comment]
Thank you!

**Comment by pthomasj** [comment]
Would you happen to have an example of reading a string camera property? For instance, how should the `device_user_id` variable be declared here?

```C
GstChildProxy* pylonsrc_child_proxy = GST_CHILD_PROXY(pylonsrc);
gst_child_proxy_get(
    pylonsrc_child_proxy,
    "cam::DeviceUserID", &device_user_id,
    NULL);
```

**Comment by pthomasj** [comment]
Thank you.

**Comment by pthomasj** [comment]
Is it possible to get the names, types and ranges for all of the accessible properties for a connected camera, so that an interface to all of them can be dynamically created dependent on the model of the camera connected to?

**Comment by pthomasj** [comment]
Is the code for [this](https://www.youtube.com/watch?v=IF4sOrmFs2A) available? I'm essentially trying to do the same thing, except for [EPICS](https://epics-controls.org/) instead of OPC-UA.

**Comment by thiesmoeller** [comment]
>Is it possible to get the names, types and ranges for all of the accessible properties for a connected camera, so that an interface to all of them can be dynamically created dependent on the model of the camera connected to?

All info is available by introspection. Currently we have one issue, that prevents you to really use it.
Here is one such GUI, that is automatically generated https://github.com/UbiCastTeam/gst-gtklaunch-1.0 ( only the issue prevents it to work properly on our plugin)

Only comment is, if you really want to have a perfect UI for the camera side, a hybrid approach of using native pylon SDK and a gst pipeline behind it will give you a way better user experience.
Main reason is, that e.g. gstreamer only has static min/max per feature. pylon SDK will also give you the correct increments and dynamically updated limits depending on the current operating point of the camera

**Comment by pthomasj** [comment]
"Only comment is, if you really want to have a perfect UI for the camera side, a hybrid approach of using native pylon SDK and a gst pipeline behind it will give you a way better user experience."

Thank you. That is actually what I have started doing now. Is there an example of using the Pylon SDK to do this?

**Comment by thiesmoeller** [comment]
https://github.com/MattsProjects/pylon_gstreamer

**Comment by pthomasj** [comment]
I'm sorry, I meant, is there an example of using the Pylon SDK to automatically generate a user interface to all of a camera's parameters.

**Comment by pthomasj** [comment]
For example, is the source for [this](https://www.youtube.com/watch?v=IF4sOrmFs2A) available?

**Comment by thiesmoeller** [comment]
As there are a lot of different options to realize such a generic user interface, can you point me to a comparable user Interface based on EPICS?
Something that you would take as a reference ?

**Comment by pthomasj** [comment]
I should probably have worded that as just interface. That is, I don't mean a GUI. In EPICS, each camera parameter would be available as a process variable channel, in the same manner as in OPC UA.

**Comment by pthomasj** [comment]
The project that I would incorporate it into is [here](https://git.ligo.org/cds/software/cameras/pylon-camera-server/-/tree/appsrc). There is currently support for controlling the exposure time and gain as EPICS channels, but I would like to be able to create channels like that dynamically, based on what parameters the camera has available.

**Comment by thiesmoeller** [comment]
Hi @pthomasj, I looked a bit into EPICS.

If I got it right:
Main concept is that you have process variables like in a PLC that are used to communicate state between components in the system.
I found no system to represent detailed data type information like in genicam ( min, max, increment, list of valid values etc ).

If this is right, and you really have "only" values, you should stay with using our gst-plugin-pylon approach. As this would give you all interaction with the stream for free.

Only task for you would be mapping of plugin parameters to pvSimple variables.
We are currently investigating if full black box introspection of the plugin really works and document this for you.

**Comment by pthomasj** [comment]
Hi @thiesmoeller,

Yes, I think that sounds right. Each process variable has a set of attributes, such as alarm level, min and max value, and numeric precision, but probably not all of those that GenICam has. I think there are structured process variables in EPICS 4, but we have not moved to that version yet.

I think at this point I am just hoping for a way to get the list of all of the attached camera parameters and their properties through the Pylon SDK. I can iterate through the GenICam node map and print the name of each node, but there are a lot of names listed like 'node xxx' that I don't understand what they correspond to.
