### ISSUE TITLE
Build on Nvidia AGX Orin Jetpack 6.0

### ISSUE THREAD

**Issue by joao-dourado** [basler/gst-plugin-pylon#92]
Hi,

I can`t build on NVIDIA Jetson AGX Orin Dev Kit Jetpack 6.0 L4T 36.2.0. Pylon 7.4.

Following the steps, when I get to:

$ ninja -C builddir test

ninja: Entering directory `builddir'
[1/2] Running all tests.
1/1 generic_states        FAIL             7.20s   killed by signal 6 SIGABRT
GST_PLUGIN_SCANNER_1_0=/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 GST_PLUGIN_PATH_1_0=/home/viposa/gst-plugin-pylon/builddir:/usr/lib/aarch64-linux-gnu/gstreamer-1.0:/usr/lib/aarch64-linux-gnu/gstreamer-1.0 MALLOC_PERTURB_=153 GST_PLUGIN_SYSTEM_PATH_1_0='' GST_PLUGIN_LOADING_WHITELIST=gstreamer:gst-plugins-base:gst-plugin-pylon@/home/viposa/gst-plugin-pylon/builddir GSETTINGS_BACKEND=memory CK_DEFAULT_TIMEOUT=20 ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 GST_REGISTRY=/home/viposa/gst-plugin-pylon/builddir/tests/check/generic_states.registry GST_STATE_IGNORE_ELEMENTS='
' /home/viposa/gst-plugin-pylon/builddir/tests/check/generic_states
―――――――――――――――――――――――――――――――――― ✀  ――――――――――――――――――――――――――――――――――
stderr:

(generic_states:15875): GStreamer-WARNING **: 08:20:11.771: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.

(generic_states:15875): GStreamer-WARNING **: 08:20:18.658: Failed to load plugin '/home/viposa/gst-plugin-pylon/builddir/bindings/pygstpylon.cpython-310-aarch64-linux-gnu.so': /home/viposa/gst-plugin-pylon/builddir/bindings/pygstpylon.cpython-310-aarch64-linux-gnu.so: undefined symbol: PyInstanceMethod_Type
GLib (gthread-posix.c): Unexpected error from C library during 'pthread_setspecific': Invalid argument.  Aborting.
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

Summary of Failures:

1/1 generic_states FAIL             7.20s   killed by signal 6 SIGABRT

Ok:                 0   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /home/viposa/gst-plugin-pylon/builddir/meson-logs/testlog.txt
FAILED: meson-internal__test 
/usr/local/bin/meson test --no-rebuild --print-errorlogs
ninja: build stopped: subcommand failed.

**Comment by erencerman** [comment]
Same here...

**Comment by thiesmoeller** [comment]
The plugin will work without issues. 

It is the core gstreamer test  runner that runs into this problem here. We can't do anything from our codebase.

Root cause is here: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/2877#note_2283535
A fix has been merged on gstreamer mainline.

So a fix for Ubuntu will be available in one of the next but the Ubuntu versions

**Comment by joao-dourado** [comment]
Thanks, also had a blacklisting problem, but it was solved following you instructions here (https://github.com/basler/gst-plugin-pylon/issues/95#issuecomment-2016867697)

But now I can't run from python using the same code I used in other Jetson versions...
When I try to run a test in terminal "$gst-launch-1.0 pylonsrc device-index=1 ! videoconvert ! queue !  autovideosink" It works, but before I get this warning, in the output:

(gst-plugin-scanner:28561): GStreamer-WARNING **: 09:02:57.959: Failed to load plugin '/home/viposa/.local/share/gstreamer-1.0/plugins/libgstpylon.so': libGCBase_gcc_v3_1_Basler_pylon.so: cannot open shared object file: No such file or directory
terminate called without an active exception
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...

Is this that preventing my old script to work?

**Comment by joao-dourado** [comment]
> Thanks, I had a blacklisting problem, but it was solved following your instructions here ([#95 (comment)](https://github.com/basler/gst-plugin-pylon/issues/95#issuecomment-2016867697))
> 
> When I run "$gst-launch-1.0 pylonsrc device-index=1 ! videoconvert ! queue ! autovideosink" Everything works, but I get this warning, in the output:
> 
> (gst-plugin-scanner:28561): GStreamer-WARNING **: 09:02:57.959: Failed to load plugin '/home/viposa/.local/share/gstreamer-1.0/plugins/libgstpylon.so': libGCBase_gcc_v3_1_Basler_pylon.so: cannot open shared object file: No such file or directory terminate called without an active exception Setting pipeline to PAUSED ... Pipeline is live and does not need PREROLL ... Pipeline is PREROLLED ... Setting pipeline to PLAYING ... New clock: GstSystemClock Redistribute latency...
> 
> If this not related, then the issue is solved.

solved here https://github.com/basler/gst-plugin-pylon/issues/95#issuecomment-2024912657
